export const marketingConfig = {
  quotes: [
    {
      quote:
        "If you can get 1% better each day for one year, you'll end up 37 times better by the time you're done.",
      author: "James Clear",
    },
    {
      quote:
        "Building habits in the present allows you to do more of what you want in the future.",
      author: "James Clear",
    },
    {
      quote:
        "Habits are like the atoms of our lives, each one is a fundamental unit that contributes to your overall improvement.",
      author: "James Clear",
    },
    {
      quote:
        "Ultimately, it's your commitment to the process that will determine your progress.",
      author: "James Clear",
    },
    {
      quote:
        "A slight change in your daily habits can guide your life to a different destination.",
      author: "James Clear",
    },
    {
      quote:
        "A habit is a routine or behaviour that is performed regularly and, in many cases, automatically.",
      author: "James Clear",
    },
  ],
  create: {
    title: "Create.",
    description: "Pick an emoji, a color, and enter your new habit.",
  },
  track: {
    title: "Track.",
    description: "Click the check icon to mark today's completion.",
  },
  update: {
    title: "Update.",
    description: "Review and mark past days by clicking on each date.",
  },
  habits: [
    "Meditate 15 min",
    "Journal before bed",
    "Read 20 pages",
    "Write 500 words",
    "Morning reflection",
    "Exercise 30 min",
    "Sleep 7-8 hours",
    "Eat 5 veggies",
    "Hydrate 8 glasses",
    "Plan before bed",
    "Organize for 10 min",
    "Learn 20 min",
    "Practice music 30 min",
    "Create art piece",
    "Save $10",
    "Budget 5 min",
    "Connect with loved one",
    "Volunteer 20 min",
    "Review accomplishments",
    "1 hour screen limit",
    "10 min walk",
    "Express gratitude",
    "Daily task list",
    "Try new recipe",
    "Quick body stretch",
    "Learn language 15 min",
    "Proud moment today",
    "Breathing exercise",
    "No screens before bed",
    "Compliment someone",
    "Floss before bed",
    "Take stairs",
    "Listen to podcast",
    "10 min in nature",
    "Positive affirmation",
    "Limit caffeine 2 PM",
    "Organize workspace",
  ],
  colors: [
    {
      id: "green-600",
      hex: "#22c55e",
    },
    {
      id: "red-600",
      hex: "#dc2626",
    },
    {
      id: "yellow-500",
      hex: "#eab308",
    },
    {
      id: "blue-500",
      hex: "#3b82f6",
    },
    {
      id: "purple-600",
      hex: "#9333ea",
    },
    {
      id: "pink-600",
      hex: "#db2777",
    },
  ],
  emojis: [
    "🔄",
    "🎯",
    "📅",
    "🌱",
    "🚀",
    "✅",
    "🌟",
    "📆",
    "🏆",
    "🌈",
    "🌞",
    "🧘‍♂️",
    "🏋️‍♀️",
    "📚",
    "🎨",
    "🚴‍♂️",
    "🍏",
    "🌿",
    "💪",
    "🌙",
    "🚶‍♀️",
    "🍎",
    "🚿",
    "🛌",
    "🎶",
    "🚭",
    "🎮",
    "🌅",
    "🌊",
    "🌄",
    "🌌",
    "🌠",
    "🎆",
    "🚲",
    "🏞️",
    "🍇",
    "🍉",
    "🏅",
    "📖",
    "🖌️",
    "🍓",
    "🌞",
    "🎨",
    "🎧",
    "🏋️‍♂️",
    "🏕️",
    "🏖️",
    "🎬",
    "📝",
  ],
};
